"""add folder to emails

Revision ID: 265b4db26c22
Revises: 
Create Date: 2026-05-07 15:42:33.113285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '265b4db26c22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('accounts_email_key'), 'accounts', type_='unique')
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.add_column('emails', sa.Column('folder', sa.Text(), nullable=True))
    op.alter_column('emails', 'uid',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('emails', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('emails', 'forwarded_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_emails_account_id'), 'emails', ['account_id'], unique=False)
    op.create_index(op.f('ix_emails_id'), 'emails', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_account_id'), table_name='emails')
    op.alter_column('emails', 'forwarded_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('emails', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('emails', 'uid',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('emails', 'folder')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.create_unique_constraint(op.f('accounts_email_key'), 'accounts', ['email'])
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
