"""add_is_read_to_emails

Revision ID: 70bb8ddfd5ac
Revises: 3eaaa225e53d
Create Date: 2026-05-09 12:39:49.470304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70bb8ddfd5ac'
down_revision: Union[str, Sequence[str], None] = '3eaaa225e53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_read', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'is_read')
    # ### end Alembic commands ###
